services:
  postgis:
    image: postgis/postgis
    environment:
      - POSTGRES_DB=gpx
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - 5432:5432
    networks:
      - default
    restart: unless-stopped

  osrm:
    image: osrm/osrm-backend
    volumes:
      - ./osrm:/data
      - ./osrm:/profiles
    networks:
      - default
    ports:
      - 6000:5000
    restart: unless-stopped
    command: >
      bash -c "
      osrm-extract -p /profiles/foot.lua /data/singapore.osm.pbf && 
      osrm-partition /data/singapore.osrm && 
      osrm-customize /data/singapore.osrm && 
      osrm-routed \
      --algorithm mld \
      --max-matching-size 20000 \
      --max-viaroute-size 20000 \
      --max-trip-size 20000 \
      --max-table-size 20000 \
      /data/singapore.osrm
      "


networks:
  default:
    driver: bridge